apiVersion: skaffold/v2beta26
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: pmofrancisco/bingo-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "pages/**/*.ts"
            dest: .
          - src: "pages/**/*.tsx"
            dest: .
    - image: pmofrancisco/bingo-auth-service
      context: auth-service
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.ts"
            dest: .
    - image: pmofrancisco/bingo-cards-service
      context: cards-service
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.ts"
            dest: .
    - image: pmofrancisco/bingo-graphql-service
      context: graphql-service
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.ts"
            dest: .
deploy:
  kubectl:
    manifests:
      - k8s/*
