apiVersion: skaffold/v2beta26
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: pmofrancisco/bingo-auth-service
      context: auth-service
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.ts"
            dest: .
    - image: pmofrancisco/bingo-cards-service
      context: cards-service
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.ts"
            dest: .
deploy:
  kubectl:
    manifests:
      - k8s/auth-deployment.yaml
      - k8s/cards-deployment.yaml
