apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: graphql-service
  template:
    metadata:
      labels:
        component: graphql-service
    spec:
      containers:
        - name: graphql-service
          image: pmofrancisco/bingo-graphql-service
          env:
            - name: AUTH_ROOT_URL
              value: 'http://auth-cluster-ip-service:3000'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          ports:
            - containerPort: 3000